<?php
namespace ResourceCatalog\Model;

interface IUserGroupIdentify
{
    const IDENTIFY = array(
        IUserGroup::ID['NULL'] => 'NULL',
        IUserGroup::ID['FZHGGWYH'] => 'FZHGGWYH',
        IUserGroup::ID['BGS'] => 'BGS',
        IUserGroup::ID['GYHJMRHJ'] => 'GYHJMRHJ',
        IUserGroup::ID['TYJRSWJ'] => 'TYJRSWJ',
        IUserGroup::ID['YJGLJ'] => 'YJGLJ',
        IUserGroup::ID['SCJDGLJ'] => 'SCJDGLJ',
        IUserGroup::ID['FPKFJ'] => 'FPKFJ',
        IUserGroup::ID['GAJ'] => 'GAJ',
        IUserGroup::ID['CZJ'] => 'CZJ',
        IUserGroup::ID['XFJ'] => 'XFJ',
        IUserGroup::ID['GYZCJDGLWYH'] => 'GYZCJDGLWYH',
        IUserGroup::ID['JYHTYJ'] => 'JYHTYJ',
        IUserGroup::ID['SFJ'] => 'SFJ',
        IUserGroup::ID['RLZYHSHBZJ'] => 'RLZYHSHBZJ',
        IUserGroup::ID['JRGZJ'] => 'JRGZJ',
        IUserGroup::ID['ZRZYHGHJ'] => 'ZRZYHGHJ',
        IUserGroup::ID['JJHZHWSJ'] => 'JJHZHWSJ',
        IUserGroup::ID['SLJ'] => 'SLJ',
        IUserGroup::ID['YLBZJ'] => 'YLBZJ',
        IUserGroup::ID['LYHZYJ'] => 'LYHZYJ',
        IUserGroup::ID['JTYSJ'] => 'JTYSJ',
        IUserGroup::ID['ZWFWHFGJJFZJ'] => 'ZWFWHFGJJFZJ',
        IUserGroup::ID['DXCKCCJSFWJ'] => 'DXCKCCJSFWJ',
        IUserGroup::ID['STHJJ'] => 'STHJJ',
        IUserGroup::ID['SWJ'] => 'SWJ',
        IUserGroup::ID['MZJ'] => 'MZJ',
        IUserGroup::ID['NYNCJ'] => 'NYNCJ',
        IUserGroup::ID['WHGBDSHLYJ'] => 'WHGBDSHLYJ',
        IUserGroup::ID['WSJKWYH'] => 'WSJKWYH',
        IUserGroup::ID['SJJ'] => 'SJJ',
        IUserGroup::ID['TJJ'] => 'TJJ',
        IUserGroup::ID['ZFHCXJSJ'] => 'ZFHCXJSJ',
        IUserGroup::ID['KXJSJ'] => 'KXJSJ',
        IUserGroup::ID['CPQFGW'] => 'CPQFGW',
        IUserGroup::ID['NXQFGW'] => 'NXQFGW',
        IUserGroup::ID['YBXFGW'] => 'YBXFGW',
        IUserGroup::ID['JAXFGW'] => 'JAXFGW',
        IUserGroup::ID['CNXFGW'] => 'CNXFGW',
        IUserGroup::ID['GXFGW'] => 'GXFGW',
        IUserGroup::ID['JLXFGW'] => 'JLXFGW',
        IUserGroup::ID['HXFGW'] => 'HXFGW',
        IUserGroup::ID['XWXFGW'] => 'XWXFGW',
        IUserGroup::ID['PSXFGW'] => 'PSXFGW',
    );
}
