<?php
namespace ResourceCatalog\Model;

interface IUserGroup extends IUserGroupIdentify
{
    const ID = array(
        'NULL' => 0,
        'FZHGGWYH' => 1,
        'BGS' => 2,
        'GYHJMRHJ' => 3,
        'TYJRSWJ' => 4,
        'YJGLJ' => 5,
        'SCJDGLJ' => 6,
        'FPKFJ' => 7,
        'GAJ' => 8,
        'CZJ' => 9,
        'XFJ' => 10,
        'GYZCJDGLWYH' => 11,
        'JYHTYJ' => 12,
        'SFJ' => 13,
        'RLZYHSHBZJ' => 14,
        'JRGZJ' => 15,
        'ZRZYHGHJ' => 16,
        'JJHZHWSJ' => 17,
        'SLJ' => 18,
        'YLBZJ' => 19,
        'LYHZYJ' => 20,
        'JTYSJ' => 21,
        'ZWFWHFGJJFZJ' => 22,
        'DXCKCCJSFWJ' => 23,
        'STHJJ' => 24,
        'SWJ' => 25,
        'MZJ' => 26,
        'NYNCJ' => 27,
        'WHGBDSHLYJ' => 28,
        'WSJKWYH' => 30,
        'SJJ' => 32,
        'TJJ' => 33,
        'ZFHCXJSJ' => 41,
        'KXJSJ' => 46,
        'CPQFGW' => 100,
        'NXQFGW' => 200,
        'YBXFGW' => 300,
        'JAXFGW' => 400,
        'CNXFGW' => 500,
        'GXFGW' => 600,
        'JLXFGW' => 700,
        'HXFGW' => 800,
        'XWXFGW' => 900,
        'PSXFGW' => 1000,
    );
}
