<?php
namespace ResourceCatalog\Model;

interface IUserGroupIdentify
{
    const IDENTIFY = array(
        IUserGroup::ID['NULL'] => 0,
        IUserGroup::ID['SFZHGGWYH'] => 'SFGW',
        IUserGroup::ID['GQTPXSW'] => 'GQTPXSW',
        IUserGroup::ID['SWMB'] => 'SWMB',
        IUserGroup::ID['RMYHPXSZXZH'] => 'RHPXZXZH',
        IUserGroup::ID['SQXJ'] => 'SQXJ',
        IUserGroup::ID['SZJRMFY'] => 'SZY',
        IUserGroup::ID['SLSJ'] => 'SLSJ',
        IUserGroup::ID['SGAJ'] => 'SGAJ',
        IUserGroup::ID['SCZJ'] => 'SCZJ',
        IUserGroup::ID['SGYHXXHWYH'] => 'SGXW',
        IUserGroup::ID['SGYZCJDGLWYH'] => 'SGZW',
        IUserGroup::ID['SJYJ'] => 'SJYJ',
        IUserGroup::ID['SSFJ'] => 'SSFJ',
        IUserGroup::ID['SRLZYHSHBZJ'] => 'SRSJ',
        IUserGroup::ID['SJSJ'] => 'SJSJ',
        IUserGroup::ID['SGHJ'] => 'SGHJ',
        IUserGroup::ID['SRQYXGS'] => 'SRQJ',
        IUserGroup::ID['SSLJ'] => 'SSLJ',
        IUserGroup::ID['SGDGS'] => 'SGDGS',
        IUserGroup::ID['SLYJ'] => 'SLYJ',
        IUserGroup::ID['SJTYSJ'] => 'SJTYSJ',
        IUserGroup::ID['SLYFZWYH'] => 'SLFW',
        IUserGroup::ID['SFDCGLJ'] => 'SFGJ',
        IUserGroup::ID['SHJBHJ'] => 'SHBJ',
        IUserGroup::ID['SSWJ'] => 'SSWJ',
        IUserGroup::ID['SMZJ'] => 'SMZJ',
        IUserGroup::ID['SNYJ'] => 'SNYJ',
        IUserGroup::ID['SWHGDXWCBS'] => 'SWGXJ',
        IUserGroup::ID['SGTZYJ'] => 'SGTZYJ',
        IUserGroup::ID['SWSHJHSYWYH'] => 'SWJW',
        IUserGroup::ID['SGJSWJ'] => 'SGJSWJ',
        IUserGroup::ID['SDFSWJ'] => 'SDFSWJ',
        IUserGroup::ID['STJJ'] => 'STJJ',
        IUserGroup::ID['SSCHZLJGGLJ'] => 'SZJJ',
        IUserGroup::ID['SAQSCJDGLJ'] => 'SAJGJ',
        IUserGroup::ID['ZGYDPXFGS'] => 'ZGYDPXFGS',
        IUserGroup::ID['PXHCZPXBZ'] => 'PXHCZPXBZ',
        IUserGroup::ID['SYJFJ'] => 'SYJFJ',
        IUserGroup::ID['SGGZWGLJ'] => 'SGGZWGLJ',
        IUserGroup::ID['ZGDXPXFGS'] => 'ZGDXPXFGS',
        IUserGroup::ID['SCSGLXZZFJ'] => 'SCGZFJ',
        IUserGroup::ID['ZGLTPXFGS'] => 'ZGLTPXFGS',
        IUserGroup::ID['SJGBZWYHBGS'] => 'SBB',
        IUserGroup::ID['STYJ'] => 'STYJ',
        IUserGroup::ID['SDAJ'] => 'SDAJ',
        IUserGroup::ID['SKXJSJ'] => 'SKJJ',
        IUserGroup::ID['SWGS'] => 'SWGS',
        IUserGroup::ID['CPQ'] => 'CPQ',
        IUserGroup::ID['NXQ'] => 'NXQ',
        IUserGroup::ID['YBX'] => 'YBX',
        IUserGroup::ID['JAX'] => 'JAX',
        IUserGroup::ID['CNX'] => 'CNX',
        IUserGroup::ID['GX'] => 'GX',
        IUserGroup::ID['JLX'] => 'JLX',
        IUserGroup::ID['HX'] => 'HX',
        IUserGroup::ID['XWX'] => 'XWX',
        IUserGroup::ID['PSX'] => 'PSX',
    );
}
